config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about_us', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources created for user-profile
  resources :users, only: [:show]
  resources :projects, except: [:destroy] do
    resources :contributions, only: [:create] # should be nested
  end
  resources :contributions, only: [:destroy]
  namespace :sponsor do
    resources :contributions
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, :last_name, :org_name, :total_points, presence: true
  has_many :projects
  has_many :contributions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  before_validation :def_total_points, on: :create

  def def_total_points
    self.total_points = 0
  end

  def sponsor?
    projects.count > 0
  end

  def user_total_points
    sum = 0
    contributions.each do |contribution|
      if contribution.status == 'accepted' && contribution.project.end_date < DateTime.now
        sum += contribution.project.points_earned
      end
    end
    return sum
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    # @projects = Project.all
    # authorize @projects
    @user_id = current_user.id
    @user_projects = Project.all.where user_id: @user_id
    authorize @user_projects

    @user_contributions = Contribution.all.where user_id: @user_id
    # authorize @user_contributions
  end
end

app/views/users/show.html.erb
  <div class="user-show-banner">
    <%# <h1><%= @project.project_name %></h1>
  </div>


        <%# Profile Container %>
        <div class="profile-page-container">

          <div class="image-container">
            <img src="https://i.pravatar.cc/300" alt="avatar-image">
          </div>

          <div class="profile-content">
            <h2><%= current_user.first_name %> <%= current_user.last_name %></h2>
            <%# <p>User Id: <%= @user_id %></p>
              <p><strong>Representing:</strong> <bdi class="content"><%= current_user.org_name %></bdi></p>
              <p><strong>Sponsoring:</strong> <bdi class="content"><%= current_user.projects.count %></bdi> projects</p>
              <p><strong>Contribution points:</strong> <bdi class="content"><%= current_user.user_total_points %></bdi> pt</p>
              <p><strong>Mission:</strong> <%= current_user.mission %></p>
          </div>
        </div>
        <%# Profile Container %>
    <%# card component for projects%>
    <div class ="user-projects-card-container">
          <%= link_to "Start a Project", new_project_path, role: "button", class: "btn btn-secondary px-4 me-md-2 position-absolute top-0 end-79" %>
        <div class="row-title-contribution">
          <h3>Projects I am Sponsoring</h3>
       </div>
      <% @user_projects.each do |project|%>
        <div class="project-card">
          <img class="profile-image" src="<%= project.photo.attached? ? cl_image_path(project.photo.key) : image_path('helping.png') %>">
          <div class="project-card-stats">
              <ul>
                <li><bdi><strong><%= project.project_name.capitalize %></strong></bdi></li>
                <li><strong>Starts:</strong> <%= project.start_date.strftime("%d/%m/%y %H:%M")  %></li>
                <li><strong>Ends:</strong> <%= project.end_date.strftime("%d/%m/%y %H:%M")  %></li>
                <li><strong>Contributors needed:</strong> <%= project.people_required %></li>
                <li class="link-button"><%= link_to 'Details', project_path(project), class: 'btn btn-secondary' %></li>
              </ul>
          </div>
        </div>
      <% end %>
    </div>





    <%# card component for contributions %>
    <div>
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="accepted projects">
          <button class="nav-link active" id="accepted-tab" data-bs-toggle="tab" data-bs-target="#accepted" type="button" role="tab" aria-controls="accepted" aria-selected="true">Accepted</button>
        </li>
        <li class="nav-item" role="pending projects">
          <button class="nav-link" id="pending-tab" data-bs-toggle="tab" data-bs-target="#pending" type="button" role="tab" aria-controls="pending" aria-selected="false">Requests Pending</button>
        </li>
        <li class="nav-item" role="denied projects">
          <button class="nav-link" id="denied-tab" data-bs-toggle="tab" data-bs-target="#denied" type="button" role="tab" aria-controls="denied" aria-selected="false">Requests Denied</button>
        </li>
      </ul>

    <%# tab content section %>
      <div class="tab-content" id="myTabContent" style="min-height: 400px">
          <div class="tab-pane fade show active" id="accepted" role="tabpanel" aria-labelledby="accepted-tab">
            <div class ="user-projects-card-container" class="row">
      <%= link_to "Contribute", projects_path, role: "button", class:  "btn btn-secondary px-4 me-md-2 position-absolute top-0 end-79" %>
    <div class="row-title">
      <h3>My Contributions to Sponsored Projects</h3>
    </div>
              <% if @user_contributions.empty? %>
                <p> No contributions planned currently </p>
              <% else %>
                <% @user_contributions.each do |contribution| %>
                  <% if contribution.status == :accepted.to_s %>
                      <div class="project-card">
                        <img class="profile-image" src="https://picsum.photos/460/250" alt="Place-holder-images">
                        <div class="project-card-stats">
                          <ol>
                            <ul><strong>Project</strong> <%= contribution.project.project_name.capitalize %></ul>
                            <ul><strong>Status:</strong> <%= contribution.status %></ul>
                            <ul class ="btn"><%= link_to 'Project detail', project_path(contribution.project_id), :class => 'btn btn-secondary' %></ul>
                          </ol>
                        </div>
                      </div>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="tab-pane fade" id="pending" role="tabpanel" aria-labelledby="pending-tab">
            <div class ="user-projects-card-container" class="row">
              <% if @user_contributions.empty? %>
                <p> No pending contribution requests </p>
              <% else %>
                <% @user_contributions.each do |contribution| %>
                  <% if contribution.status == :pending.to_s %>
                      <div class="project-card">
                        <img class="profile-image" src="https://picsum.photos/460/250" alt="Place-holder-images">
                        <div class="project-card-stats">
                          <ol>
                            <ul><strong>Project</strong> <%= contribution.project.project_name.capitalize %></ul>
                            <ul><strong>Status:</strong> <%= contribution.status %></ul>
                            <ul class ="btn"><%= link_to 'Project detail', project_path(contribution.project_id), :class => 'btn btn-secondary' %></ul>
                          </ol>
                        </div>
                      </div>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="tab-pane fade" id="denied" role="tabpanel" aria-labelledby="denied-tab">
            <div class ="user-projects-card-container" class="row">
              <% if @user_contributions.empty? %>
                <p> No contribution requests denied </p>
              <% else %>
                <% @user_contributions.each do |contribution| %>
                  <% if contribution.status == :denied.to_s %>
                    <div class="project-card">
                      <img class="profile-image" src="https://picsum.photos/460/250" alt="Place-holder-images">
                      <div class="project-card-stats">
                        <ol>
                          <ul><strong>Project</strong> <%= contribution.project.project_name.capitalize %></ul>
                          <ul><strong>Status:</strong> <%= contribution.status %></ul>
                          <ul class ="btn"><%= link_to 'Project detail', project_path(contribution.project_id), :class => 'btn btn-secondary' %></ul>
                        </ol>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
      </div>
    </div>
</div>

</div>