config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about_us', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources created for user-profile
  resources :users, only: [:show]
  resources :projects, except: [:destroy] do
    resources :contributions, only: [:create] # should be nested
  end
  resources :contributions, only: [:destroy]
  namespace :sponsor do
    resources :contributions
  end
end

app/views/shared/_footer.html.erb
<footer class="text-center">
  <ul class="list_inline">
    <li>
      <a class="logo" href="#">
        <i class="fab fa-facebook"></i>
      </a>
    </li>
    <li>
      <a class="logo" href="#">
        <i class="fab fa-instagram"></i>
      </a>
    </li>
    <li>
      <a class="logo" href="#">
        <i class="fab fa-linkedin"></i>
      </a>
    </li>
  </ul>
  <%# <p>Powered by RBBE-corp.</p> %>
  <p>Copyright <i class="far fa-copyright"></i> 2022 RBBE-Corp. All Rights Reserved.</p>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-lewagon shadow p-3 bg-body">
  <div class="container-fluid px-5">
    <%= link_to root_path, class: "navbar-brand" do %>
      <span class= "colabo-logo"> <%= image_tag "logo3.png" %></span>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div  class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to "About", about_us_path, class: "nav-link" %>
          </li>
          <li class="nav-item ">
            <%= link_to "Projects", projects_path, class: "nav-link" %>
          </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "My Profile", current_user, class: "nav-link" %>
          </li>
          <li class="nav-item" style="font-size: 1.05em">
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link button-square-right logout" %>
          </li>
        <% else %>
          <li class="nav-item" style="font-size: 1.05em">
            <%= link_to "Log In", new_user_session_path, class: "nav-link button-square-right login" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>