config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about_us', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources created for user-profile
  resources :users, only: [:show]
  resources :projects, except: [:destroy] do
    resources :contributions, only: [:create] # should be nested
  end
  resources :contributions, only: [:destroy]
  namespace :sponsor do
    resources :contributions
  end
end

app/views/pages/about.html.erb
<div class="container pt-5">
  <div class="about-us p-3 rounded">
    <h3 class="fw-bold" style="text-align: center">About Us</h3>
    <p class="text-white">In today's modern era, where people have more access to information and communication networks than any other time in history,
    perhaps we are more distant and separate from each other than ever before.
    </p>
    <p class="text-white">Our team's mission is to help forge positive and constructive bonds within communities,
    by promoting social responsibilty through collaborative projects.
    We also aim to encourage top down participation and support through government and corporate sponsorship of such projects.
    </p>
  </div>

  <div class="team-box">
     <h1 class="h1-text">
      <i class="fa fa-users" aria-hidden="true"></i>Team Members
    </h1>
    <div class="container">
      <div class="content-box">
        <div class="top-bar"></div>
        <div class="top">
          <i class="fa fa-check-circle" aria-hidden="true"></i>
          <input type="checkbox" class="heart-btn" id="heart-btn-1">
          <label class="heart" for="heart-btn-1"></label>
        </div>
        <div class="content">
          <img src="https://avatars.githubusercontent.com/u/86738640?v=4" alt="">
          <strong>Reona Kasuya</strong>
          <p>kasuyareona@gmail.com</p>
        </div>
        <div class="btn">
          <a href="https://github.com/Reona001"><i class="fab fa-github" aria-hidden="true"></i>Github</a>
          <a href="#"><i class="fa fa-eye" aria-hidden="true"></i>View</a>
        </div>
      </div>
      <div class="content-box">
        <div class="top-bar"></div>
        <div class="top">
          <div>
            <i class="fa fa-check-circle" aria-hidden="true"></i>
          </div>
          <div>
            <input type="checkbox" class="heart-btn" id="heart-btn-2">
            <label class="heart" for="heart-btn-2"></label>
          </div>
        </div>
        <div class="content">
          <img src="https://avatars.githubusercontent.com/u/78086454?v=4" alt="">
          <strong>Byron Lee</strong>
          <p>leebyron@gmail.com</p>
        </div>
        <div class="btn">
          <a href="https://github.com/switchloops"><i class="fab fa-github" aria-hidden="true"></i>Github</a>
          <a href="#"><i class="fa fa-eye" aria-hidden="true"></i>View</a>
        </div>
      </div>
      <div class="content-box">
        <div class="top-bar"></div>
        <div class="top">
          <i class="fa fa-check-circle" aria-hidden="true"></i>
          <input type="checkbox" class="heart-btn" id="heart-btn-3">
          <label class="heart" for="heart-btn-3"></label>
        </div>
        <div class="content">
          <img src="https://avatars.githubusercontent.com/u/37336776?v=4" alt="">
          <strong>Erika Kawashima</strong>
          <p>kawashimaerika@gmail.com</p>
        </div>
        <div class="btn">
          <a href="https://github.com/marshallekm"><i class="fab fa-github" aria-hidden="true"></i>Github</a>
          <a href="#"><i class="fa fa-eye" aria-hidden="true"></i>View</a>
        </div>
      </div>
      <div class="content-box">
        <div class="top-bar"></div>
        <div class="top">
          <i class="fa fa-check-circle" aria-hidden="true"></i>
          <input type="checkbox" class="heart-btn" id="heart-btn-4">
          <label class="heart" for="heart-btn-4"></label>
        </div>
        <div class="content">
          <img src="https://avatars.githubusercontent.com/u/83071733?v=4" alt="">
          <strong>Babin Bohora</strong>
          <p>bohorababin@gmail.com</p>
        </div>
        <div class="btn">
          <a href="https://github.com/nibab-boo"><i class="fab fa-github" aria-hidden="true"></i>Github</a>
          <a href="#"><i class="fa fa-eye" aria-hidden="true"></i>View</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/components.html.erb
<h1>Welcome to components</h1>

app/views/pages/home.html.erb
<div class="w-100 bg-white" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(<%= image_path 'clean_park_1.jpg'%>)">
  <div class="container col-xxl-8 px-4 py-5">
    <div class="px-4 my-5 text-center">
    <%# <img class="d-block mx-auto mb-4" src="/docs/5.1/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57"> %>
      <span class= "d-block mx-auto mb-4 ms-5"> <%= image_tag "logo_lightblue.svg", :width => '300', :height => '240' %></span>
    <%# <h1 class="display-5 fw-bold">Colabo</h1> %>
    <div class="col-lg-6 mx-auto">
      <h2 class="slogan-text" class="lead mb-4 px-3">Cultivating a Caring Community</h2>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <%# <button type="button" class="btn btn-primary btn-lg px-4 gap-3">Primary button</button>
        <button type="button" class="btn btn-outline-secondary btn-lg px-4">Secondary</button> %>
        <%= link_to "Start a Project", new_project_path, role: "button", class: "btn btn-primary m-3 px-4 me-md-2"%>
        <%= link_to "Contribute", projects_path, role: "button", class: "btn btn-secondary m-3 px-4"%>
      </div>
    </div>
  </div>
    <!--<div class="row flex-lg-row-reverse align-items-center g-5 py-5">
      <div class="col-10 col-sm-8 col-lg-6">
        <%= image_tag image_path('help.png'), alt: "help" %>
      </div>
      <div class="col-lg-6">
        <div class="lc-block mb-3">
          <div editable="rich">
            <h1>Colabo</h1>
            <h2 class="fw-bold display-5">Cultivate a Caring Community with <span class="text-danger">Colabo</span></h2>
          </div>
        </div>

        <div class="lc-block mb-3">
          <div editable="rich">
            <p class="lead"><span class="h3 fw-bold text-primary "><%= image_tag "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flat_tick_icon.svg/768px-Flat_tick_icon.svg.png", alt: "easy", width: "52px" %></span><span class="h3 fw-bold mx-3 text-primary"><%= image_tag "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Font_Awesome_5_solid_shipping-fast.svg/1279px-Font_Awesome_5_solid_shipping-fast.svg.png", alt: "fast", width: "52px" %></span><span class="h3 fw-bold text-primary"><span class="h3 fw-bold text-primary "><%= image_tag "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/OOjs_UI_icon_secure-link.svg/1024px-OOjs_UI_icon_secure-link.svg.png", alt: "safe", width: "52px" %></span>
            <p class="lead"><span class="h3 fw-bold text-secondary ">Easy</span><span class="h3 fw-bold mx-3 text-secondary">Fast</span><span class="h3 fw-bold text-secondary">Safe</span>
            </p>
          </div>
        </div>

        <div class="lc-block d-grid gap-2 d-md-flex justify-content-md-start">
          <%# <a class="btn btn-primary px-4 me-md-2" href="#" role="button">Click me, I'm a button</a> %>
          <%= link_to "Start a Project", new_project_path, role: "button", class: "btn btn-primary px-4 me-md-2"%>
          <%= link_to "Contribute", projects_path, role: "button", class: "btn btn-outline-secondary px-4"%>
          <%# <a class="btn btn-outline-secondary px-4" href="#" role="button">Click me, I'm a button</a> %>
        </div>

      </div>
    </div> -->
  </div>
</div>
<div class="container" style= "margin-top: 50px">
  <div class="box">
   <div class="text-center mb-3">
    <span class="h5 inline-block text-secondary fw-bold px-3 py-1" style="background: rgb(231,233,237); border-radius:8px">How it works</span>
  </div>
  <div class="how_we_work shadow py-5 px-3 mb-5 bg-white">
    <h3 class="text-center fw-bold">Create, and Contribute to, Sponsored Community Events</h3>
    <div class="row justify-content-center">
      <div class="col-sm-6 col-md-4 col-xs-12 text-center">
        <div class="svg-box">
          <%= render 'components/project_svg' %>
        </div>
        <div class="work-note">
          <p><strong>Become an Project Sponsor</strong></p>
          <p>As a sponsor representing an organisation, create a sponsored event to help your local community,
          and offer rewards to people willing to volunteer their time</p>
        </div>
      </div>
      <div class="col-sm-6 col-md-4 col-xs-12 text-center">
        <div class="svg-box">
          <%= render 'components/contribution_svg' %>
        </div>
        <div class="work-note">
          <p><strong>Be a Contributor</strong></p>
          <p>Search for other sponsored events that you would like to
          participate in and support with your time and effort</p>
        </div>
      </div>
      <div class="col-sm-6 col-md-4 col-xs-12 text-center">
        <div class="svg-box">
          <%= render 'components/reward_svg' %>
        </div>
        <div class="work-note">
          <p><strong>Manage Project and Contribution lists</strong></p>
          <p>Curate contributor requests to projects that you are sponsoring,
          and see the progress of your requests to contribute on other sponsored projects</p>
        </div>
      </div>
    </div>
    </div>
  </div>

  <div class="w-100" style="margin: 100px auto">
    <div class="text-center mb-3">
      <span class="h5 inline-block text-secondary fw-bold px-3 py-1" style="background: rgb(231,233,237); border-radius:8px">Our Featured Projects</span>
    </div>
    <div class="row justify-content-center">
      <div class="wrapper how_we_work shadow py-5 px-3 mb-5">
        <div class="carousel">
        <% @projects.each do |project| %>
          <div class="carousel__item">
            <%# <div class="carousel__item-head">😀</div> %>
            <div class="carousel__item-body">
              <img class="profile-image mx-auto" height="160" style="width: 100%; object-fit: cover" src=<%= project.photo.attached? ? cl_image_path(project.photo.key) : image_path('help.png') %>>
              <p><%= link_to project.project_name, project, class: "title inline-block h5 text-center text-dark fw-bold"  %></p>
              <!--<h6 class="card-subtitle mb-2 text-muted"><%= project.user.first_name %></h6>-->
              <!--<p class="card-text"><%= project.description %></p>-->
              <p class="card-text text-muted">Held on: <%= project.start_date %></p>
              <p class="card-text text-warning">Contributors: <%= project.accepted.count %>/<%= project.people_required %></p>
            </div>
          </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="w-100" style="margin: 100px auto">
    <div class="text-center mb-3">
      <span class="h5 inline-block text-secondary fw-bold px-3 py-1" style="background: rgb(231,233,237); border-radius:8px">Find Sponsored Projects Near You</span>
    </div>
    <div class="how_we_work shadow py-5 px-3 mb-5">
      <div class="row justify-content-center">
        <div class="map-container row justify-content-center">
          <div id="map"
            class="main-map"
            style="width: 50%; height: 600px;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        </div>
      </div>
    </div>
  </div>
</div>

<%# if current user has a project show the contributions page %>
<!-- <% if current_user && current_user.sponsor? %>
  <p><%= link_to 'Contributions', sponsor_contributions_path %></p>
  <p><%= link_to 'Projects', projects_path %></p>
  <p><%= link_to 'User Profile', user_path(current_user) %></p>
<% end %> -->