config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about_us', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources created for user-profile
  resources :users, only: [:show]
  resources :projects, except: [:destroy] do
    resources :contributions, only: [:create] # should be nested
  end
  resources :contributions, only: [:destroy]
  namespace :sponsor do
    resources :contributions
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  validates :project_name, presence: true, uniqueness: true
  validates :description, presence: true, length: { maximum: 2000 }
  validates :people_required, presence: true, inclusion: { in: 1..100 }
  validates :location, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :reward_earned, presence: true
  validates :points_earned, presence: true, numericality: { only_integer: true }
  validates :user_id, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  has_many :contributions

  validate :start_date_cannot_be_after_end_date,
     :start_date_cannot_be_before_today

  def start_date_cannot_be_after_end_date
    if start_date > end_date
      errors.add(:start_date, "can't be after end date")
    end
  end

  def start_date_cannot_be_before_today
    if start_date < DateTime.now
      errors.add(:start_date, "can't be before today")
    end
  end


  def self.contributions_count
    left_joins(:contributions)
    .group(:id)
    .order('COUNT(contributions.id) DESC')
    .limit(10)
  end

  def find_users
    users_array = []
    contributions.each do | contribution |
      users_array << contribution.user
    end
    users_array
  end

  def find_contribution(contributor)
    Contribution.all.where("project_id = ? AND user_id = ?", id, contributor.id).first # SQL Array
  end

  #pg search
  include PgSearch::Model
  pg_search_scope :search_by_project_and_location,
    against: [ :project_name, :description, :location ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }


  def ends_in_future?
    end_date > DateTime.now
  end

  def accepted
    accepted = contributions.select { |contribution| contribution.status == "accepted"}
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :find_project, only: [:show, :edit, :update]

  def index
    # @projects = Project.all
    # @projects = policy_scope(Project)
    if params[:query].present?
      @projects = policy_scope(Project).search_by_project_and_location(params[:query])
   else
     @projects = policy_scope(Project)
   end
  end

  def show
    @markers = [@project.geocode].map do |lat, lng|
    { lat: lat,
      lng: lng }
    end
  end

  def new
    @project = Project.new
    authorize @project
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    authorize @project
    if @project.save
      redirect_to project_path(@project), notice: "Project created."
    else
      render :new
    end
  end

  def edit; end

  def update
    if @project.update(project_params)
      redirect_to project_path, notice: "Project updated."
    else
      render :edit
    end
  end

  private

  def project_params
    params.require(:project).permit(:project_name, :description, :people_required, :location, :start_date, :end_date, :reward_earned, :points_earned, :photo)
  end

  def find_project
    @project = Project.find(params[:id])
    authorize @project
  end
end

app/views/projects/edit.html.erb
<div class="w-50 mx-auto">
  <%= render 'components/project-form'  %>
</div>

app/views/projects/index.html.erb
<%# Banner Component %>

<div class="projects-banner">
  <div class="project-title-container">
    <h1>Upcoming Projects</h1>
    <div class="search-bar-container">
      <div class="search-bar">
        <%= form_tag projects_path,class: "row g-3", method: :get do %>
          <div class="col-auto">
                  <%= text_field_tag :query,
                  params[:query],
                  class: "form-control",
                  placeholder: "Find projects"
                  %>
          </div>
          <div class="col-auto">
            <%= submit_tag "Search", class: "btn btn-primary mb-3" %>
          </div>
        <% end %>
      </div>
     </div>

    <%# <%= @incomplete = Project.all.where( Project.people_required == Project.contributions_count) %>

    <div class="title-bar-element">
     <p><bdi><strong><%= Project.all.count %></strong></bdi> ongoing projects that you can help with.</p>
    </div>

    <div class="title-bar-element">
     <p><bdi><strong><%= User.all.count %></strong></bdi> users helping the community.</p>
    </div>

    <div class="title-bar-element">
     <p><bdi><strong><%= Contribution.all.count %></strong></bdi> contibutions being made.</p>
    </div>

</div>



<%# card component %>
<div class ="projects-master-container">
  <div class ="projects-card-container">
    <% @projects.each do |project|%>
      <div class="project-card">
        <img class="profile-image" src="<%= project.photo.attached? ? cl_image_path(project.photo.key) : image_path('helping.png') %>">
        <div class="project-card-stats">
            <ul>
              <li><bdi><strong><%= project.project_name.capitalize %></strong></bdi></li>
              <li><strong>Sponsor:</strong> <%= project.user.org_name %></li>
              <li><strong>Contributors needed: </strong><%= project.contributions.count %>/<%= project.people_required %></li>
              <li class="link-button"><%= link_to 'Details', project_path(project), class: 'btn btn-secondary' %></li>
            </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="form-container">
    <div class="w-50 mx-auto shadow py-5 my-5 bg-body rounded">
      <h2>Create your project </h2>
      <%= render 'components/project-form'  %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container-show">
  <div class="show-banner">
    <h1><%= @project.project_name %></h1>
</div>

<div class="project">
  <div class="row justify-content-around">

   <div class="section-arrow">
    <%= link_to user_path(current_user) do %>
      <i class="fas fa-arrow-left fa-2x"></i>
    <%end%>
    </div>

    <div class="description col-12 col-md-4">
    <img class="profile-image" src=<%= @project.photo.attached? ? cl_image_path(@project.photo.key) : image_path('help.png') %>>
    <h3> <%= @project.description %> </h3>
    </div>

  <div class="col-12 col-md-4">
  <div class="map-container">
    <div id="map"
      data-status="main-map"
      style="width: 100%; height: 400px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>

<div class="information-section">
   <p> People required for project: <%= @project.people_required %></p>
    <p> Total contributors: <%= @project.contributions.count %></p>
    <p> Location: <%= @project.location %> </p>
    <p> Starts: <%= @project.start_date %> </p>
    <p> Ends: <%= @project.end_date %> </p>
    <p> Rewards: <%= @project.reward_earned %></p>
    <p> Points: <%= @project.points_earned %></p>
</div>


  <div class="project-buttons">
    <% if @project.ends_in_future? %>
      <% if @project.user_id == current_user.id %>
        <p><%= link_to 'Edit Project', edit_project_path, class: 'btn btn-secondary' %></p>
      <% elsif @project.find_users.include?(current_user) %>
        <p><%= link_to 'Cancel Contribution Request', contribution_path(@project.find_contribution(current_user)), method: :delete, class: 'btn btn-secondary' %> </p>
      <% end %>
    <% end %>
    <% if @project.user_id != current_user.id && @project.find_users.exclude?(current_user) %>
      <% if @project.start_date > DateTime.now %>
        <p><%= link_to 'Make Contribution Request', project_contributions_path(@project), method: :post, class: 'btn btn-secondary' %></p>
      <% else %>
        <div class="already-started"><p>Project already started, cannot contribute</p></div>
      <% end %>
    <% end %>
      </div>
    </div>
  </div>
</div>


<%# Contribution Cards %>
<% if current_user == @project.user %>

<div class="container mt-5">
  <div class="bg-white">
    <h1>Contribution requests</h1>
  </div>

  <%# card component for contributions %>
  <div>
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="accepted projects">
        <button class="nav-link active" id="accepted-tab" data-bs-toggle="tab" data-bs-target="#accepted" type="button" role="tab" aria-controls="accepted" aria-selected="true">Accepted</button>
      </li>
      <li class="nav-item" role="pending projects">
        <button class="nav-link" id="pending-tab" data-bs-toggle="tab" data-bs-target="#pending" type="button" role="tab" aria-controls="pending" aria-selected="false">Requests Pending</button>
      </li>
      <li class="nav-item" role="denied projects">
        <button class="nav-link" id="denied-tab" data-bs-toggle="tab" data-bs-target="#denied" type="button" role="tab" aria-controls="denied" aria-selected="false">Requests Denied</button>
      </li>
    </ul>

  <%# tab content section %>
    <div class="tab-content shadow p-3 mb-5 rounded" id="myTabContent" style="min-height: 400px">
        <div class="tab-pane fade show active" id="accepted" role="tabpanel" aria-labelledby="accepted-tab">
          <div class ="contribution-cards-holder p-3" class="row">
            <% if @project.contributions.empty? %>
              <p> No contributions planned currently </p>
            <% else %>
              <% @project.contributions.each do |contribution| %>
                <% if contribution.status == :accepted.to_s %>
                  <div class="contribution-card">
                    <img class="profile-image" src="https://picsum.photos/460/250" alt="Place-holder-images">
                    <div class="profile-content">
                          <ul>
                            <li><strong>Contributor:</strong> <%= contribution.user.first_name%> <%= contribution.user.last_name %></li>
                            <li><strong>Status:</strong> <%= contribution.status %></li>
                            <li class="simple form">
                                <% if contribution.status == :pending %>
                                  <%= simple_form_for(contribution, as: :contribution, method: :patch, url: sponsor_contribution_path(contribution)) do |f| %>
                                    <%= f.input :status, :as => :hidden, :input_html => { :value => "accepted" }%>
                                    <%= f.button :submit, "Accept" %>
                                  <% end %>
                                  <%= simple_form_for(contribution, as: :contribution, method: :patch, url: sponsor_contribution_path(contribution)) do |f| %>
                                    <%= f.input :status, :as => :hidden, :input_html => { :value => "denied" }%>
                                    <%= f.button :submit, "Deny" %>
                                  <% end %>
                                <% else %>
                                  <li class="link-button"><%= contribution.status %></li>
                                <% end %>
                            <%# <li class="link-button"><%= link_to 'Details (to contribution#show)', sponsor_contribution_path(contribution), class: 'btn btn-secondary' %></li>
                            </li>
                          </ul>
                      </div>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
          <div class="tab-pane fade" id="pending" role="tabpanel" aria-labelledby="pending-tab">
            <div class ="contribution-cards-holder p-3" class="row">
              <% if @project.contributions.empty? %>
                <p> No pending contribution requests </p>
              <% else %>
                <% @project.contributions.each do |contribution| %>
                  <% if contribution.status == :pending.to_s %>
                    <div class="contribution-card">
                      <img class="profile-image" src="https://picsum.photos/460/250" alt="Place-holder-images">
                      <div class="profile-content">
                        <ul>
                          <li><strong>Contributor:</strong> <%= contribution.user.first_name%> <%= contribution.user.last_name %></li>
                          <li><strong>Status:</strong> <%= contribution.status %></li>
                          <li class="simple form">
                            <% if contribution.status == :pending.to_s %>
                              <%= simple_form_for(contribution, as: :contribution, method: :patch, url: sponsor_contribution_path(contribution)) do |f| %>
                                <%= f.input :status, :as => :hidden, :input_html => { :value => "accepted" }%>
                                <%= f.button :submit, "Accept" %>
                              <% end %>
                              <%= simple_form_for(contribution, as: :contribution, method: :patch, url: sponsor_contribution_path(contribution)) do |f| %>
                                <%= f.input :status, :as => :hidden, :input_html => { :value => "denied" }%>
                                <%= f.button :submit, "Deny" %>
                              <% end %>
                            <% else %>
                              <li class="link-button"><%= contribution.status %></li>
                            <% end %>
                          <%# <li class="link-button"><%= link_to 'Details (to contribution#show)', sponsor_contribution_path(contribution), class: 'btn btn-secondary' %></li>
                          </li>
                        </ul>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        <div class="tab-pane fade" id="denied" role="tabpanel" aria-labelledby="denied-tab">
          <div class ="contribution-cards-holder p-3" class="row">
            <% if @project.contributions.empty? %>
              <p> No contribution requests denied </p>
            <% else %>
              <% @project.contributions.each do |contribution| %>
                <% if contribution.status == :denied.to_s %>
                  <div class="contribution-card">
                    <img class="profile-image" src="https://picsum.photos/460/250" alt="Place-holder-images">
                    <div class="profile-content">
                          <ul>
                            <li><strong>Contributor:</strong> <%= contribution.user.first_name%> <%= contribution.user.last_name %></li>
                            <li><strong>Status:</strong> <%= contribution.status %></li>
                            <li class="simple form">
                                <% if contribution.status == :pending %>
                                  <%= simple_form_for(contribution, as: :contribution, method: :patch, url: sponsor_contribution_path(contribution)) do |f| %>
                                    <%= f.input :status, :as => :hidden, :input_html => { :value => "accepted" }%>
                                    <%= f.button :submit, "Accept" %>
                                  <% end %>
                                  <%= simple_form_for(contribution, as: :contribution, method: :patch, url: sponsor_contribution_path(contribution)) do |f| %>
                                    <%= f.input :status, :as => :hidden, :input_html => { :value => "denied" }%>
                                    <%= f.button :submit, "Deny" %>
                                  <% end %>
                                <% else %>
                                  <li class="link-button"><%= contribution.status %></li>
                                <% end %>
                            <%# <li class="link-button"><%= link_to 'Details (to contribution#show)', sponsor_contribution_path(contribution), class: 'btn btn-secondary' %></li>
                            </li>
                          </ul>
                      </div>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
    </div>
  </div>
</div>
<% end %>